/* eslint-disable */
export const data = [
  {
    id: 1,
    name: 'The Tides At Arverne By The Sea',
    image: 'https://photos.zillowstatic.com/fp/00ca20c0f040f67e66bfc6738275e5fa-cc_ft_1152.webp',
    price: 3100.0,
    location: '190 Beach 69th St, Arverne, NY 11692',
    description: 'A new architectural masterpiece now dazzles the shores of the Rockaways with the addition of THE TIDES at Arverne By The Sea. Spectacular beachfront, affordable & luxurious apartments, offering modern open living spaces and high-end finishes.\n\n Amenities will include a roof deck with pool and lounge, indoor and outdoor dining experiences, private parking available for a fee, bike storage and more.',
    bedroom_number: 3,
    user_id: 7,
    created_at: '2023-04-07T14:45:25.938Z',
    updated_at: '2023-04-07T14:45:25.938Z',
  },
  {
    id: 2,
    name: 'The Tides At Arverne By The Sea',
    image: 'https://photos.zillowstatic.com/fp/00ca20c0f040f67e66bfc6738275e5fa-cc_ft_1152.webp',
    price: 3100.0,
    location: '190 Beach 69th St, Arverne, NY 11692',
    description: 'A new architectural masterpiece now dazzles the shores of the Rockaways with the addition of THE TIDES at Arverne By The Sea. Spectacular beachfront, affordable & luxurious apartments, offering modern open living spaces and high-end finishes.\n\n Amenities will include a roof deck with pool and lounge, indoor and outdoor dining experiences, private parking available for a fee, bike storage and more.',
    bedroom_number: 3,
    user_id: 8,
    created_at: '2023-04-07T14:53:37.217Z',
    updated_at: '2023-04-07T14:53:37.217Z',
  },
  {
    id: 3,
    name: 'The Tides At Arverne By The Sea',
    image: 'https://photos.zillowstatic.com/fp/00ca20c0f040f67e66bfc6738275e5fa-cc_ft_1152.webp',
    price: 3100.0,
    location: '190 Beach 69th St, Arverne, NY 11692',
    description: 'A new architectural masterpiece now dazzles the shores of the Rockaways with the addition of THE TIDES at Arverne By The Sea. Spectacular beachfront, affordable & luxurious apartments, offering modern open living spaces and high-end finishes.\n\n Amenities will include a roof deck with pool and lounge, indoor and outdoor dining experiences, private parking available for a fee, bike storage and more.',
    bedroom_number: 3,
    user_id: 9,
    created_at: '2023-04-07T15:01:52.144Z',
    updated_at: '2023-04-07T15:01:52.144Z',
  },
  // {
  //   id: 4,
  //   name: 'The Tides At Arverne By The Sea',
  //   image: 'https://photos.zillowstatic.com/fp/00ca20c0f040f67e66bfc6738275e5fa-cc_ft_1152.webp',
  //   price: 3100.0,
  //   location: '190 Beach 69th St, Arverne, NY 11692',
  //   description: 'A new architectural masterpiece now dazzles the shores of the Rockaways with the addition of THE TIDES at Arverne By The Sea. Spectacular beachfront, affordable & luxurious apartments, offering modern open living spaces and high-end finishes.\n\n Amenities will include a roof deck with pool and lounge, indoor and outdoor dining experiences, private parking available for a fee, bike storage and more.',
  //   bedroom_number: 3,
  //   user_id: 10,
  //   created_at: '2023-04-07T15:03:21.327Z',
  //   updated_at: '2023-04-07T15:03:21.327Z',
  // },
];


